# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Pymdu
copyright: Copyright &copy; 2024 Tipee
nav:
  - Accueil: index.md
  - Installation: installation.md
  - Documentation: documentation.md
  - API Références: references.md
  - Demos: demo_data_inputs.ipynb
site_url: https://pymdu.plateforme-tipee.com
site_description: website
repo_url: https://gitlab.plateforme-tipee.com/mdu/pymdu
watch:
  - pymdu
  - docs
extra:
  generator: false
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  logo: img/logo-pymdu.png
  favicon: img/favicon.ico
  custom_dir: docs/overrides
  language: fr
  icon:
    repo: fontawesome/brands/gitlab
  palette:
    - scheme: default
      primary:
        accent: indigo
        toggle:
          icon: material/lightbulb
          name: Switch to dark mode
  highlightjs: true
  hljs_languages:
    - bash
    - python
  font:
    text: 'Roboto'
    code: 'Inconsolata'
  features:
    - toc.follow
    - toc.integrate
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.instant.progress
    - content.footnote.tooltips
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link

plugins:
  #  - my_plugin:
  #      definition_file: configs/test.ini  # relative to mkdocs.yml
  #      validation:
  #        enabled: !ENV [ CI, false ]
  #        verbose: true
  #        skip_checks:
  #          - foo
  #          - baz
  - mkdocs-jupyter:
      include: [ "*.ipynb" ]
      ignore_h1_titles: true
      execute: true
      kernel_name: python3
      include_source: true
      include_requirejs: true
      custom_mathjax_url: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-AMS_CHTML-full,Safe"
  - autorefs
  #  - mkdocs-autoapi:
  #      autoapi_dir: docs/autoapi
  #      autoapi_file_patterns:
  #        - "*.py"
  - rss:
      abstract_chars_count: 160  # -1 for full content
      abstract_delimiter: <!-- more -->
      categories:
        - tags
      comments_path: "#__comments"
      date_from_meta:
        as_creation: "date" # means from page.meta.date
        as_update: "git" # means from git log
        datetime_format: "%Y-%m-%d %H:%M"
        default_time: "09:30"
        default_timezone: Europe/Paris
      enabled: true
      feed_description: "My custom feed description"  # MkDocs site_description: will be used if this key is not present
      feeds_filenames:
        json_created: feed_json_created.json
        json_updated: feed_json_updated.json
        rss_created: feed_rss_created.xml
        rss_updated: feed_rss_updated.xml
      feed_title: "My custom feed title"  # MkDocs site_name: will be used if this key is not present
      feed_ttl: 1440
      image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
      json_feed_enabled: true
      length: 20
      match_path: ".*"
      pretty_print: false
      rss_feed_enabled: true
      url_parameters:
        utm_source: "documentation"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"
      use_git: true
      use_material_social_cards: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          extensions:
            - griffe_typingdoc
          rendering:
            show_category_heading: true
            show_source: false
            heading_level: 1
            show_root_toc_entry: true
          paths: [ "pymdu/geometric", "pymdu/physics/umep", "pymdu/meteo" ]  # search packages in the src folder
          options:
            docstring_section_style: spacy
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
              trim_doctest_flags: true
            show_root_heading: true
            show_if_no_docstring: false
            show_source: false
            preload_modules:
              - pandas
              - geopandas
            inherited_members: false
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            filters:
              - '!^_'
            merge_init_into_class: true
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
  - search:
      lang: fr
markdown_extensions:
  - attr_list
  - md_in_html
  - abbr
  - tables
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
      base_path: [ docs/snippets, "." ]
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.extra
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.blocks.tab
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: python
          class: python
          validator: !!python/name:markdown_exec.validator
          format: !!python/name:markdown_exec.formatter
hooks:
  - docs/hooks/copy_dir.py
  - docs/hooks/breadcrumb.py
draft_docs: |
  - docs/hooks.py