from distutils.dir_util import copy_tree


def on_pre_build(config):
    print("Pre-build: Starting to build the site!")


def on_post_build(config):
    # copy_tree("jupyterlite", "site/jupyterlite")
    print("Post-build: Finished building the site!")


def on_page_markdown(markdown, page, config, files):
    # Modify markdown before it is converted to HTML
    print(f"Processing page: {page.file.src_path}")
    # Example: add a footer to every page
    footer = "\n\n---\nGenerated by MkDocs"
    return markdown + footer
